package gui;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.List;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.DBModel;
import model.IModel;
import model.Kerdes;

/**
 *
 * @author Mező Gábor 1995.mg@gmail.com
 */
public class FoAblak extends javax.swing.JFrame {

    private IModel model;
    private List<Kerdes> kerdesek;
    private DefaultTableModel dtm;
    private int id;
    private int nyeremenyErtek;
    private String osszeg;

    public FoAblak() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Legyen Ön is milliomos!");
        getContentPane().setBackground(Color.black);
        String dbURL = "jdbc:mysql://localhost:3306/loim";
        String dbUser = "root";
        String dbPass = "1234";
        try {

            Connection conn = DriverManager.getConnection(dbURL, dbUser, dbPass);
            model = new DBModel(conn);
            kerdesek = model.getAllKerdes();
        } catch (SQLException ex) {
            hibaAblak(ex);
        }
        kerdes();
        nyeremenyErtek = 14;
        nyeremenyFrissit(nyeremenyErtek);
        osszegKi.setText("Jelenlegi Nyeremény: " + osszeg);
    }

    public void kerdes() {

        Random rnd = new Random();
        id = rnd.nextInt(kerdesek.size());

        jlabelKerdes.setText(kerdesek.get(id).getSzoveg());
        btnValasz0.setText("A: " + kerdesek.get(id).getValaszok().get(0));
        btnValasz1.setText("B: " + kerdesek.get(id).getValaszok().get(1));
        btnValasz2.setText("C: " + kerdesek.get(id).getValaszok().get(2));
        btnValasz3.setText("D: " + kerdesek.get(id).getValaszok().get(3));
    }
//Jlist select modosítás

    public void nyeremenyFrissit(int nyeremenyID) {

        jList1.setSelectedIndex(nyeremenyID);
        jList1.setForeground(Color.orange);
        jList1.setSelectionBackground(Color.gray);
        osszeg = (String) jList1.getSelectedValue();

    }
//Válaszok vizsgálata

    public void valaszVizs(int kivalasztott) {
        if (kivalasztott == kerdesek.get(id).getHelyesValasz()) {
            nyeremenyErtek--;
            nyeremenyFrissit(nyeremenyErtek);
            osszegKi.setText("Jelenlegi Nyeremény: " + osszeg);
            if (nyeremenyErtek == 0) {
                helyesAblak("Helyes válasz! Megnyerte a játékot!\n Nyereménye: " + osszeg
                        + " ! Gratulalunk!" + "\n Új játék indítása?");
            } else {
                helyesValsz("Helyes valasz!\n Összeg " + osszeg + " nyert!\n Következő kérdés ");
                if (kerdesek.size() > 2) {
                    kerdesek.remove(id);
                }

                kerdes();
            }
        } else {
            helytelenAblak("A valasz helytelen! \n A jateknak vege. \n "
                    + " \n Új játék indítása?");

            nyeremenyErtek = 14;
            nyeremenyFrissit(nyeremenyErtek);
            osszegKi.setText("Jelenlegi Nyeremény: " + osszeg);

        }
    }
//egyéni hiba ablak

    public static void hibaAblak(Exception ex) {
        JOptionPane.showMessageDialog(null, ex.toString(), "Hiba történt",
                JOptionPane.ERROR_MESSAGE);
    }

    public void helytelenAblak(String uzenet) {
        Object[] options = {"Igen", "Nem"};

        int valasz = JOptionPane.showOptionDialog(null, uzenet.toString(), "Helytelen Válasz!", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
        if (valasz == JOptionPane.YES_OPTION) {   //Igen-t nyomott a dialoguson

            kerdes();
        } else {
            System.exit(0);
        }
    }

    public void helyesAblak(String uzenet) {
        Object[] options = {"Igen", "Nem"};

        int valasz = JOptionPane.showOptionDialog(null, uzenet.toString(), "Helyes Válasz!", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
        if (valasz == JOptionPane.YES_OPTION) {   //Igen-t nyomott a dialoguson

            kerdes();
        } else {
            System.exit(0);
        }
    }

    public void helyesValsz(String uzenet) {
        JOptionPane.showMessageDialog(null, uzenet.toString(), "Helyes Válasz!",
                JOptionPane.PLAIN_MESSAGE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        btnValasz0 = new javax.swing.JButton();
        btnValasz1 = new javax.swing.JButton();
        btnValasz2 = new javax.swing.JButton();
        btnValasz3 = new javax.swing.JButton();
        jlabelKerdes = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlabelKerdes1 = new javax.swing.JLabel();
        osszegKi = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jList1.setBackground(new java.awt.Color(0, 0, 0));
        jList1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jList1.setForeground(new java.awt.Color(255, 255, 255));
        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "40 000 000Ft", "20 000 000Ft", "10 000 000Ft", "5 000 000Ft", "3 000 000Ft", "1 500 000Ft", "800 000Ft", "500 000Ft", "300 000Ft", "200 000Ft", "100 000Ft", "50 000Ft", "20 000Ft", "10 000Ft", "5 000Ft" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.setDropMode(javax.swing.DropMode.ON);
        jList1.setRequestFocusEnabled(false);
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        btnValasz0.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnValasz0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValasz0ActionPerformed(evt);
            }
        });

        btnValasz1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnValasz1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValasz1ActionPerformed(evt);
            }
        });

        btnValasz2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnValasz2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValasz2ActionPerformed(evt);
            }
        });

        btnValasz3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnValasz3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValasz3ActionPerformed(evt);
            }
        });

        jlabelKerdes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlabelKerdes.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));

        jlabelKerdes1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        osszegKi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        osszegKi.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\XeonSkorp\\Desktop\\TanfolyamProject\\SwingMilliomosRe\\src\\gui\\kep.jpg")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlabelKerdes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnValasz1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnValasz0, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnValasz2, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnValasz3, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(41, 41, 41)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(52, 52, 52))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(osszegKi, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
                                        .addGap(256, 256, 256)))))))
                .addGap(75, 75, 75))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(87, Short.MAX_VALUE)
                    .addComponent(jlabelKerdes1, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(290, 290, 290)))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnValasz0, btnValasz1, btnValasz2, btnValasz3});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(osszegKi, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addComponent(jlabelKerdes, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnValasz0, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnValasz2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnValasz1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnValasz3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(430, Short.MAX_VALUE)
                    .addComponent(jlabelKerdes1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(144, 144, 144)))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnValasz0, btnValasz1, btnValasz2, btnValasz3});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnValasz0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValasz0ActionPerformed
        valaszVizs(0);
    }//GEN-LAST:event_btnValasz0ActionPerformed

    private void btnValasz1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValasz1ActionPerformed
        valaszVizs(1);
    }//GEN-LAST:event_btnValasz1ActionPerformed

    private void btnValasz2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValasz2ActionPerformed
        valaszVizs(2);
    }//GEN-LAST:event_btnValasz2ActionPerformed

    private void btnValasz3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValasz3ActionPerformed
        valaszVizs(3);
    }//GEN-LAST:event_btnValasz3ActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jList1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FoAblak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FoAblak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FoAblak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FoAblak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FoAblak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnValasz0;
    private javax.swing.JButton btnValasz1;
    private javax.swing.JButton btnValasz2;
    private javax.swing.JButton btnValasz3;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlabelKerdes;
    private javax.swing.JLabel jlabelKerdes1;
    private javax.swing.JLabel osszegKi;
    // End of variables declaration//GEN-END:variables
}
